name: docker image

on:
  workflow_dispatch:
    inputs:
      PGCLI_VERSION:
        description: "pgcli version"
        required: true
        default: "3.5.0"
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            PGCLI_VERSION=${{ inputs.PGCLI_VERSION }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/pgcli:latest
            ghcr.io/${{ github.repository_owner }}/pgcli:${{ inputs.PGCLI_VERSION }}
